
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ProjectBase.LubanGen
{
public sealed partial class CharacterConfig : Luban.BeanBase
{
    public CharacterConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Pic = _buf.ReadInt();
        HpInc = _buf.ReadInt();
        Name = _buf.ReadString();
        Sexual = _buf.ReadInt();
        Level = _buf.ReadInt();
        Exp = _buf.ReadInt();
        MaxHp = _buf.ReadInt();
        Weapon = _buf.ReadInt();
        Armor = _buf.ReadInt();
        MpType = _buf.ReadInt();
        MaxMp = _buf.ReadInt();
        Attack = _buf.ReadInt();
        Qinggong = _buf.ReadInt();
        Defence = _buf.ReadInt();
        Heal = _buf.ReadInt();
        UsePoison = _buf.ReadInt();
        DePoison = _buf.ReadInt();
        AntiPoison = _buf.ReadInt();
        Quanzhang = _buf.ReadInt();
        Yujian = _buf.ReadInt();
        Shuadao = _buf.ReadInt();
        Qimen = _buf.ReadInt();
        Anqi = _buf.ReadInt();
        Wuxuechangshi = _buf.ReadInt();
        Pinde = _buf.ReadInt();
        AttackPoison = _buf.ReadInt();
        Zuoyouhubo = _buf.ReadInt();
        IQ = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); Skills = new System.Collections.Generic.List<LRoleSkill>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { LRoleSkill _e0;  _e0 = global::ProjectBase.LubanGen.LRoleSkill.DeserializeLRoleSkill(_buf); Skills.Add(_e0);}}
        {int n0 = _buf.ReadSize(); Items = new System.Collections.Generic.List<LRoleItem>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { LRoleItem _e0;  _e0 = global::ProjectBase.LubanGen.LRoleItem.DeserializeLRoleItem(_buf); Items.Add(_e0);}}
        LeaveStoryId = _buf.ReadInt();
    }

    public static CharacterConfig DeserializeCharacterConfig(ByteBuf _buf)
    {
        return new CharacterConfig(_buf);
    }

    /// <summary>
    /// 代号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 头像/战斗代号
    /// </summary>
    public readonly int Pic;
    /// <summary>
    /// 生命增长
    /// </summary>
    public readonly int HpInc;
    /// <summary>
    /// 姓名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 性别
    /// </summary>
    public readonly int Sexual;
    /// <summary>
    /// 等级
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 经验值
    /// </summary>
    public readonly int Exp;
    /// <summary>
    /// 生命最大值
    /// </summary>
    public readonly int MaxHp;
    /// <summary>
    /// 武器
    /// </summary>
    public readonly int Weapon;
    /// <summary>
    /// 防具
    /// </summary>
    public readonly int Armor;
    /// <summary>
    /// 内力性质
    /// </summary>
    public readonly int MpType;
    /// <summary>
    /// 内力最大值
    /// </summary>
    public readonly int MaxMp;
    /// <summary>
    /// 攻击力
    /// </summary>
    public readonly int Attack;
    /// <summary>
    /// 轻功
    /// </summary>
    public readonly int Qinggong;
    /// <summary>
    /// 防御力
    /// </summary>
    public readonly int Defence;
    /// <summary>
    /// 医疗
    /// </summary>
    public readonly int Heal;
    /// <summary>
    /// 用毒
    /// </summary>
    public readonly int UsePoison;
    /// <summary>
    /// 解毒
    /// </summary>
    public readonly int DePoison;
    /// <summary>
    /// 抗毒
    /// </summary>
    public readonly int AntiPoison;
    /// <summary>
    /// 拳掌
    /// </summary>
    public readonly int Quanzhang;
    /// <summary>
    /// 御剑
    /// </summary>
    public readonly int Yujian;
    /// <summary>
    /// 耍刀
    /// </summary>
    public readonly int Shuadao;
    /// <summary>
    /// 特殊兵器
    /// </summary>
    public readonly int Qimen;
    /// <summary>
    /// 暗器技巧
    /// </summary>
    public readonly int Anqi;
    /// <summary>
    /// 武学常识
    /// </summary>
    public readonly int Wuxuechangshi;
    /// <summary>
    /// 品德
    /// </summary>
    public readonly int Pinde;
    /// <summary>
    /// 攻击带毒
    /// </summary>
    public readonly int AttackPoison;
    /// <summary>
    /// 左右互搏
    /// </summary>
    public readonly int Zuoyouhubo;
    /// <summary>
    /// 资质
    /// </summary>
    public readonly int IQ;
    /// <summary>
    /// 所会武功（所会武功ID,等级）
    /// </summary>
    public readonly System.Collections.Generic.List<LRoleSkill> Skills;
    /// <summary>
    /// 携带物品（携带物品ID，数量）
    /// </summary>
    public readonly System.Collections.Generic.List<LRoleItem> Items;
    /// <summary>
    /// 离场对话
    /// </summary>
    public readonly int LeaveStoryId;
   
    public const int __ID__ = 676994987;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Skills) { _e?.ResolveRef(tables); }
        foreach (var _e in Items) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Pic:" + Pic + ","
        + "HpInc:" + HpInc + ","
        + "Name:" + Name + ","
        + "Sexual:" + Sexual + ","
        + "Level:" + Level + ","
        + "Exp:" + Exp + ","
        + "MaxHp:" + MaxHp + ","
        + "Weapon:" + Weapon + ","
        + "Armor:" + Armor + ","
        + "MpType:" + MpType + ","
        + "MaxMp:" + MaxMp + ","
        + "Attack:" + Attack + ","
        + "Qinggong:" + Qinggong + ","
        + "Defence:" + Defence + ","
        + "Heal:" + Heal + ","
        + "UsePoison:" + UsePoison + ","
        + "DePoison:" + DePoison + ","
        + "AntiPoison:" + AntiPoison + ","
        + "Quanzhang:" + Quanzhang + ","
        + "Yujian:" + Yujian + ","
        + "Shuadao:" + Shuadao + ","
        + "Qimen:" + Qimen + ","
        + "Anqi:" + Anqi + ","
        + "Wuxuechangshi:" + Wuxuechangshi + ","
        + "Pinde:" + Pinde + ","
        + "AttackPoison:" + AttackPoison + ","
        + "Zuoyouhubo:" + Zuoyouhubo + ","
        + "IQ:" + IQ + ","
        + "Skills:" + Luban.StringUtil.CollectionToString(Skills) + ","
        + "Items:" + Luban.StringUtil.CollectionToString(Items) + ","
        + "LeaveStoryId:" + LeaveStoryId + ","
        + "}";
    }
}
}

