
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ProjectBase.LubanGen
{
/// <summary>
/// 角色物品信息
/// </summary>
public sealed partial class LRoleItem : Luban.BeanBase
{
    public LRoleItem(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Count = _buf.ReadInt();
    }

    public static LRoleItem DeserializeLRoleItem(ByteBuf _buf)
    {
        return new LRoleItem(_buf);
    }

    public readonly int Id;
    public readonly int Count;
   
    public const int __ID__ = -129852139;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Count:" + Count + ","
        + "}";
    }
}
}

