
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ProjectBase.LubanGen
{
/// <summary>
/// 角色技能信息
/// </summary>
public sealed partial class LRoleSkill : Luban.BeanBase
{
    public LRoleSkill(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Level = _buf.ReadInt();
    }

    public static LRoleSkill DeserializeLRoleSkill(ByteBuf _buf)
    {
        return new LRoleSkill(_buf);
    }

    public readonly int Id;
    public readonly int Level;
   
    public const int __ID__ = 278521999;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Level:" + Level + ","
        + "}";
    }
}
}

