
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ProjectBase.LubanGen
{
public partial class Tables
{
    public TbCharacterData TbCharacterData {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbCharacterData = new TbCharacterData(loader("tbcharacterdata"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbCharacterData.ResolveRef(this);
    }
}

}
