
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ProjectBase.LubanGen
{
public partial class TbCharacterData
{
    private readonly System.Collections.Generic.Dictionary<int, CharacterConfig> _dataMap;
    private readonly System.Collections.Generic.List<CharacterConfig> _dataList;
    
    public TbCharacterData(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, CharacterConfig>(n);
        _dataList = new System.Collections.Generic.List<CharacterConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            CharacterConfig _v;
            _v = global::ProjectBase.LubanGen.CharacterConfig.DeserializeCharacterConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, CharacterConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<CharacterConfig> DataList => _dataList;

    public CharacterConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public CharacterConfig Get(int key) => _dataMap[key];
    public CharacterConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

